### ISSUE TITLE
plone.session install breaks on ES6

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.session#23]
I tried coredev 6.0 with the ES6 PLIP. Database was copied from coredev 5.2 on Python 3, and then upgraded. In one Plone site I had all extra modules installed, like placeful workflow and `plone.session`. When viewing it I got an `error while rendering plone.resourceregistries.styles` at the top of the page, which resulted in an unstyled page.

Same is true for the standard Plone 5.2 site that I upgraded to Plone 6 ES6. Worked fine at first, but then I activated `plone.session`:

```
-03-22 21:52:31,736 INFO    [Products.GenericSetup.tool:1404][waitress-2] Importing profile profile-plone.session:default with dependency strategy upgrade.
2022-03-22 21:52:31,736 INFO    [Products.GenericSetup.tool:1445][waitress-2] Applying main profile profile-plone.session:default
2022-03-22 21:52:31,739 INFO    [GenericSetup.rolemap:100][waitress-2] Role / permission map imported.
2022-03-22 21:52:31,756 INFO    [Products.CMFPlone.resources.browser.combine:104][waitress-2] Wrote combined JS bundle "default".
2022-03-22 21:52:31,757 INFO    [Products.CMFPlone.resources.browser.combine:104][waitress-2] Wrote combined JS bundle "logged-in".
2022-03-22 21:52:31,758 INFO    [Products.CMFPlone.resources.browser.combine:136][waitress-2] Wrote combined CSS bundle "default".
2022-03-22 21:52:31,758 INFO    [Products.CMFPlone.resources.browser.combine:136][waitress-2] Wrote combined CSS bundle "logged-in".
2022-03-22 21:52:31,758 INFO    [Products.CMFPlone.resources.browser.combine:164][waitress-2] Finished bundle compilation.
2022-03-22 21:52:31,785 ERROR   [Products.CMFPlone.resources.browser.resource:136][waitress-3] Bundle 'plone-session-js' has a non existing dependeny on 'plone-logged-in'. Bundle dependency (JS) graceful rewritten to 'plone' Fallback will be removed in Plone 7.
2022-03-22 21:52:31,792 WARNING [Products.CMFPlone.resources.utils:44][waitress-3] Could not find resource acl_users/session/refresh?session_refresh=true&type=css&minutes=5. You may have to create it first.
2022-03-22 21:52:31,792 ERROR   [plone.app.viewletmanager:114][waitress-3] Error while rendering viewlet-manager=plone.htmlhead.links, viewlet=plone.resourceregistries.styles
Traceback (most recent call last):
  File "/Users/maurits/shared-eggs/cp39/plone.app.viewletmanager-3.1.2-py3.9.egg/plone/app/viewletmanager/manager.py", line 110, in render
    html.append(viewlet.render())
  File "/Users/maurits/community/plone-coredev/es6/src/plone.app.layout/plone/app/layout/viewlets/common.py", line 79, in render
    return self.index()
  File "/Users/maurits/community/plone-coredev/es6/src/Products.CMFPlone/Products/CMFPlone/resources/browser/resource.py", line 343, in index
    rendered = self.renderer["css"].render()
  File "/Users/maurits/shared-eggs/cp39/webresource-1.0b8-py3.9.egg/webresource/_api.py", line 619, in render
    return u'\n'.join([
  File "/Users/maurits/shared-eggs/cp39/webresource-1.0b8-py3.9.egg/webresource/_api.py", line 620, in <listcomp>
    res.render(self.base_url) for res in self.resolver.resolve()
  File "/Users/maurits/shared-eggs/cp39/webresource-1.0b8-py3.9.egg/webresource/_api.py", line 380, in render
    'href': self.resource_url(base_url),
  File "/Users/maurits/shared-eggs/cp39/webresource-1.0b8-py3.9.egg/webresource/_api.py", line 182, in resource_url
    parts.append(self.unique_key)
  File "/Users/maurits/shared-eggs/cp39/webresource-1.0b8-py3.9.egg/webresource/_api.py", line 167, in unique_key
    str(uuid.uuid5(namespace_uuid, self.file_hash))
  File "/Users/maurits/shared-eggs/cp39/webresource-1.0b8-py3.9.egg/webresource/_api.py", line 155, in file_hash
    hash_ = base64.b64encode(hash_func(self.file_data).digest()).decode()
TypeError: object supporting the buffer API required
```

**Comment by mauritsvanrees** [comment]
The error remains after deactivating `plone.session`. This might be a problem in its uninstall.
